version: '3.9'
services:
  mongodb:
    image: mongo:4.4.12
    restart: always
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=api
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"     
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/api --quiet
      interval: 10s
      timeout: 5s
      retries: 3
  api:
    build: 
      context: .
      dockerfile: DockerfileJar
    container_name: api-mongo-poc
    restart: always
    ports:
      - "8090:8080"
    depends_on:
      - mongodb
    volumes:
      - ./logs:/app/logs
             
networks:
    default:
        name: mongodb_network
        
volumes:
  mongo-data:        
