spring:
  data:
    mongodb:
      uri: mongodb://root:rootpassword@mongodb:27017/api?directConnection=true&authSource=admin
  jackson:
    serialization:
      fail-on-empty-beans: false
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher    
      
logging:
  file:
    name: logs/api-log.log
  pattern:
    console:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'      
  