spring:
  profiles:
    active: debug  
  application:
    name: mongo-poc
  sleuth:
    sampler:
      probability: 1.0  
 
onboarding:
  sistema:
    - description: MOTO
      code: 5
    - description: AUTO
      code: 10
    - description: CICLO
      code: 15