spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/test
      username: root
      password: example 
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher    
      
logging:
  file:
    name: logs/api-log.log
  pattern:
    console:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'      
  