openapi: 3.0.0
info:
  version: 1.0.0
  title: API de Cliente

paths:
  /clientes:
    get:
      summary: Retorna todos os clientes cadastrados
      responses:
        '200':
          description: Lista de todos os clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cliente'
    post:
      summary: Cria um novo cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
      responses:
        '201':
          description: Cliente criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'

  /clientes/{id}:
    get:
      summary: Retorna um cliente pelo ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID do cliente a ser buscado
          schema:
            type: string
      responses:
        '200':
          description: Cliente encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
        '404':
          description: Cliente não encontrado
    put:
      summary: Atualiza um cliente pelo ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID do cliente a ser atualizado
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
      responses:
        '200':
          description: Cliente atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
        '404':
          description: Cliente não encontrado
    delete:
      summary: Deleta um cliente pelo ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID do cliente a ser deletado
          schema:
            type: string
      responses:
        '204':
          description: Cliente deletado com sucesso
        '404':
          description: Cliente não encontrado

components:
  schemas:
    Endereco:
      type: object
      properties:
        logradouro:
          type: string
        estado:
          type: string
        municipio:
          type: string
        bairro:
          type: string
        cep:
          type: string
        complemento:
          type: string

    Telefone:
      type: object
      properties:
        ddd:
          type: string
        numero:
          type: string
        tipo:
          type: string
          enum: ['comercial', 'residencial', 'contato']
        principal:
          type: boolean

    Cliente:
      type: object
      properties:
        id:
          type: string
        nome:
          type: string
        sobrenome:
          type: string
        email:
          type: string
        sexo:
          type: string
          enum: ['masculino', 'feminino']
        datanascimento:
          type: string
        enderecos:
          type: array
          items:
            $ref: '#/components/schemas/Endereco'
        telefones:
          type: array
